name: Sync to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: rsync deployment
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          remote_path: /root/
          remote_host: ${{ vars.SERVER_IP }}
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
